# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sunless_skies.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.horizontalLayout_3.addWidget(self.pushButton_Open)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_3.addWidget(self.pushButton_Save)
        self.pushButton_About = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_About.setObjectName("pushButton_About")
        self.horizontalLayout_3.addWidget(self.pushButton_About)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_LoadedFile = QtWidgets.QLabel(self.centralwidget)
        self.label_LoadedFile.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_LoadedFile.setObjectName("label_LoadedFile")
        self.horizontalLayout_2.addWidget(self.label_LoadedFile)
        self.label_LoadedFileName = QtWidgets.QLabel(self.centralwidget)
        self.label_LoadedFileName.setObjectName("label_LoadedFileName")
        self.horizontalLayout_2.addWidget(self.label_LoadedFileName)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_stats = QtWidgets.QWidget()
        self.tab_stats.setObjectName("tab_stats")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_stats)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_Modifier_Veils = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Veils.setObjectName("lineEdit_Modifier_Veils")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Veils, 9, 5, 1, 1)
        self.lineEdit_Lvl_Terror = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Terror.setObjectName("lineEdit_Lvl_Terror")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Terror, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_stats)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 11, 6, 1, 1)
        self.lineEdit_Modifier_Hearts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Hearts.setObjectName("lineEdit_Modifier_Hearts")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Hearts, 8, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_stats)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 8, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_stats)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_stats)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 10, 4, 1, 1)
        self.label_Terror = QtWidgets.QLabel(self.tab_stats)
        self.label_Terror.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Terror.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Terror.setObjectName("label_Terror")
        self.gridLayout_2.addWidget(self.label_Terror, 3, 0, 1, 1)
        self.lineEdit_Modifier_Iron = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Iron.setObjectName("lineEdit_Modifier_Iron")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Iron, 10, 5, 1, 1)
        self.label_Sovereigns = QtWidgets.QLabel(self.tab_stats)
        self.label_Sovereigns.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Sovereigns.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Sovereigns.setObjectName("label_Sovereigns")
        self.gridLayout_2.addWidget(self.label_Sovereigns, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_stats)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_stats)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 11, 4, 1, 1)
        self.label_Crew = QtWidgets.QLabel(self.tab_stats)
        self.label_Crew.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Crew.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Crew.setObjectName("label_Crew")
        self.gridLayout_2.addWidget(self.label_Crew, 5, 0, 1, 1)
        self.label_Date = QtWidgets.QLabel(self.tab_stats)
        self.label_Date.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Date.setObjectName("label_Date")
        self.gridLayout_2.addWidget(self.label_Date, 6, 0, 1, 1)
        self.label_SecretComp = QtWidgets.QLabel(self.tab_stats)
        self.label_SecretComp.setMaximumSize(QtCore.QSize(110, 40))
        self.label_SecretComp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_SecretComp.setObjectName("label_SecretComp")
        self.gridLayout_2.addWidget(self.label_SecretComp, 16, 0, 1, 1)
        self.label_Hull = QtWidgets.QLabel(self.tab_stats)
        self.label_Hull.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hull.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hull.setObjectName("label_Hull")
        self.gridLayout_2.addWidget(self.label_Hull, 4, 0, 1, 1)
        self.label_Veils = QtWidgets.QLabel(self.tab_stats)
        self.label_Veils.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Veils.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Veils.setObjectName("label_Veils")
        self.gridLayout_2.addWidget(self.label_Veils, 9, 0, 1, 1)
        self.label_Hold = QtWidgets.QLabel(self.tab_stats)
        self.label_Hold.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hold.setObjectName("label_Hold")
        self.gridLayout_2.addWidget(self.label_Hold, 7, 0, 1, 1)
        self.label_Hearts = QtWidgets.QLabel(self.tab_stats)
        self.label_Hearts.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hearts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hearts.setObjectName("label_Hearts")
        self.gridLayout_2.addWidget(self.label_Hearts, 8, 0, 1, 1)
        self.label_Condition = QtWidgets.QLabel(self.tab_stats)
        self.label_Condition.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Condition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Condition.setObjectName("label_Condition")
        self.gridLayout_2.addWidget(self.label_Condition, 17, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_stats)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_Exp = QtWidgets.QLabel(self.tab_stats)
        self.label_Exp.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Exp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Exp.setObjectName("label_Exp")
        self.gridLayout_2.addWidget(self.label_Exp, 15, 0, 1, 1)
        self.label_Mirrors = QtWidgets.QLabel(self.tab_stats)
        self.label_Mirrors.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Mirrors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Mirrors.setObjectName("label_Mirrors")
        self.gridLayout_2.addWidget(self.label_Mirrors, 11, 0, 1, 1)
        self.label_Iron = QtWidgets.QLabel(self.tab_stats)
        self.label_Iron.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Iron.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Iron.setObjectName("label_Iron")
        self.gridLayout_2.addWidget(self.label_Iron, 10, 0, 1, 1)
        self.label_CharPoints = QtWidgets.QLabel(self.tab_stats)
        self.label_CharPoints.setMaximumSize(QtCore.QSize(110, 20))
        self.label_CharPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CharPoints.setObjectName("label_CharPoints")
        self.gridLayout_2.addWidget(self.label_CharPoints, 13, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_stats)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        self.lineEdit_Modifier_Hold = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Hold.setObjectName("lineEdit_Modifier_Hold")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Hold, 7, 5, 1, 1)
        self.label_CharLevel = QtWidgets.QLabel(self.tab_stats)
        self.label_CharLevel.setMaximumSize(QtCore.QSize(110, 20))
        self.label_CharLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CharLevel.setObjectName("label_CharLevel")
        self.gridLayout_2.addWidget(self.label_CharLevel, 12, 0, 1, 1)
        self.lineEdit_Lvl_Sovereigns = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Sovereigns.setObjectName("lineEdit_Lvl_Sovereigns")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Sovereigns, 1, 3, 1, 1)
        self.lineEdit_Lvl_CharLvl = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_CharLvl.setObjectName("lineEdit_Lvl_CharLvl")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_CharLvl, 12, 3, 1, 1)
        self.lineEdit_Lvl_CharPts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_CharPts.setObjectName("lineEdit_Lvl_CharPts")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_CharPts, 13, 3, 1, 1)
        self.lineEdit_Modifier_Mirrors = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Mirrors.setObjectName("lineEdit_Modifier_Mirrors")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Mirrors, 11, 5, 1, 1)
        self.lineEdit_Lvl_Hull = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Hull.setObjectName("lineEdit_Lvl_Hull")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Hull, 4, 3, 1, 1)
        self.lineEdit_Lvl_Crew = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Crew.setObjectName("lineEdit_Lvl_Crew")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Crew, 5, 3, 1, 1)
        self.lineEdit_Lvl_Date = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Date.setObjectName("lineEdit_Lvl_Date")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Date, 6, 3, 1, 1)
        self.lineEdit_Lvl_Veils = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Veils.setObjectName("lineEdit_Lvl_Veils")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Veils, 9, 3, 1, 1)
        self.lineEdit_Lvl_SecretComp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_SecretComp.setObjectName("lineEdit_Lvl_SecretComp")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_SecretComp, 16, 3, 1, 1)
        self.lineEdit_Lvl_Condition = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Condition.setObjectName("lineEdit_Lvl_Condition")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Condition, 17, 3, 1, 1)
        self.lineEdit_Lvl_Exp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Exp.setObjectName("lineEdit_Lvl_Exp")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Exp, 15, 3, 1, 1)
        self.lineEdit_Lvl_Mirrors = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Mirrors.setObjectName("lineEdit_Lvl_Mirrors")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Mirrors, 11, 3, 1, 1)
        self.lineEdit_Modifier_Hull = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Hull.setObjectName("lineEdit_Modifier_Hull")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Hull, 4, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_stats)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 4, 1, 1)
        self.lineEdit_Lvl_Iron = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Iron.setObjectName("lineEdit_Lvl_Iron")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Iron, 10, 3, 1, 1)
        self.lineEdit_Lvl_Hearts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Hearts.setObjectName("lineEdit_Lvl_Hearts")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Hearts, 8, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_stats)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 7, 4, 1, 1)
        self.lineEdit_Modifier_SecretComp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_SecretComp.setObjectName("lineEdit_Modifier_SecretComp")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_SecretComp, 16, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_stats)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 16, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_stats)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 15, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_stats)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 9, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_stats)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 13, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_stats)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 10, 6, 1, 1)
        self.lineEdit_Effective_Sovereigns = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Sovereigns.setReadOnly(True)
        self.lineEdit_Effective_Sovereigns.setObjectName("lineEdit_Effective_Sovereigns")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Sovereigns, 1, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_stats)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 6, 1, 1)
        self.lineEdit_Effective_Hold = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Hold.setReadOnly(True)
        self.lineEdit_Effective_Hold.setObjectName("lineEdit_Effective_Hold")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Hold, 7, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_stats)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_stats)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 7, 6, 1, 1)
        self.lineEdit_Effective_Date = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Date.setReadOnly(True)
        self.lineEdit_Effective_Date.setObjectName("lineEdit_Effective_Date")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Date, 6, 7, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_stats)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 8, 6, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_stats)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 16, 6, 1, 1)
        self.lineEdit_Effective_Terror = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Terror.setReadOnly(True)
        self.lineEdit_Effective_Terror.setObjectName("lineEdit_Effective_Terror")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Terror, 3, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_stats)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 6, 1, 1)
        self.lineEdit_Effective_Veils = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Veils.setReadOnly(True)
        self.lineEdit_Effective_Veils.setObjectName("lineEdit_Effective_Veils")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Veils, 9, 7, 1, 1)
        self.lineEdit_Effective_Crew = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Crew.setReadOnly(True)
        self.lineEdit_Effective_Crew.setObjectName("lineEdit_Effective_Crew")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Crew, 5, 7, 1, 1)
        self.lineEdit_Effective_CharPts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_CharPts.setReadOnly(True)
        self.lineEdit_Effective_CharPts.setObjectName("lineEdit_Effective_CharPts")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_CharPts, 13, 7, 1, 1)
        self.lineEdit_Effective_Hull = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Hull.setReadOnly(True)
        self.lineEdit_Effective_Hull.setObjectName("lineEdit_Effective_Hull")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Hull, 4, 7, 1, 1)
        self.lineEdit_Effective_Mirrors = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Mirrors.setReadOnly(True)
        self.lineEdit_Effective_Mirrors.setObjectName("lineEdit_Effective_Mirrors")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Mirrors, 11, 7, 1, 1)
        self.lineEdit_Effective_Hearts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Hearts.setReadOnly(True)
        self.lineEdit_Effective_Hearts.setObjectName("lineEdit_Effective_Hearts")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Hearts, 8, 7, 1, 1)
        self.lineEdit_Effective_CharLvl = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_CharLvl.setReadOnly(True)
        self.lineEdit_Effective_CharLvl.setObjectName("lineEdit_Effective_CharLvl")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_CharLvl, 12, 7, 1, 1)
        self.lineEdit_Effective_Exp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Exp.setReadOnly(True)
        self.lineEdit_Effective_Exp.setObjectName("lineEdit_Effective_Exp")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Exp, 15, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_stats)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 12, 6, 1, 1)
        self.lineEdit_Effective_Iron = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Iron.setReadOnly(True)
        self.lineEdit_Effective_Iron.setObjectName("lineEdit_Effective_Iron")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Iron, 10, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_stats)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_stats)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 6, 1, 1)
        self.lineEdit_Lvl_Hold = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Hold.setObjectName("lineEdit_Lvl_Hold")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Hold, 7, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_stats)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 17, 6, 1, 1)
        self.lineEdit_Effective_SecretComp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_SecretComp.setReadOnly(True)
        self.lineEdit_Effective_SecretComp.setObjectName("lineEdit_Effective_SecretComp")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_SecretComp, 16, 7, 1, 1)
        self.lineEdit_Effective_Condition = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Condition.setReadOnly(True)
        self.lineEdit_Effective_Condition.setObjectName("lineEdit_Effective_Condition")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Condition, 17, 7, 1, 1)
        self.tabWidget.addTab(self.tab_stats, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_Region = QtWidgets.QComboBox(self.tab)
        self.comboBox_Region.setObjectName("comboBox_Region")
        self.horizontalLayout_4.addWidget(self.comboBox_Region)
        self.comboBox_Port = QtWidgets.QComboBox(self.tab)
        self.comboBox_Port.setObjectName("comboBox_Port")
        self.horizontalLayout_4.addWidget(self.comboBox_Port)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_FoW_Albion = QtWidgets.QCheckBox(self.tab)
        self.checkBox_FoW_Albion.setObjectName("checkBox_FoW_Albion")
        self.gridLayout_3.addWidget(self.checkBox_FoW_Albion, 1, 0, 1, 1)
        self.checkBox_FoW_Reach = QtWidgets.QCheckBox(self.tab)
        self.checkBox_FoW_Reach.setObjectName("checkBox_FoW_Reach")
        self.gridLayout_3.addWidget(self.checkBox_FoW_Reach, 0, 0, 1, 1)
        self.checkBox_FoW_Eleutheria = QtWidgets.QCheckBox(self.tab)
        self.checkBox_FoW_Eleutheria.setObjectName("checkBox_FoW_Eleutheria")
        self.gridLayout_3.addWidget(self.checkBox_FoW_Eleutheria, 0, 1, 1, 1)
        self.checkBox_FoW_BlueKingdom = QtWidgets.QCheckBox(self.tab)
        self.checkBox_FoW_BlueKingdom.setObjectName("checkBox_FoW_BlueKingdom")
        self.gridLayout_3.addWidget(self.checkBox_FoW_BlueKingdom, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.toolBox = QtWidgets.QToolBox(self.tab_2)
        self.toolBox.setStyleSheet("QToolBox,\n"
"QToolBox > QScrollArea,\n"
"QToolBox > QScrollArea > #qt_scrollarea_viewport > QWidget {\n"
"background: transparent;\n"
"}")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 558, 69))
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_31 = QtWidgets.QLabel(self.page)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.page)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 2, 3, 1, 1)
        self.lineEdit_Poss_Academe_Specimen = QtWidgets.QLineEdit(self.page)
        self.lineEdit_Poss_Academe_Specimen.setObjectName("lineEdit_Poss_Academe_Specimen")
        self.gridLayout_5.addWidget(self.lineEdit_Poss_Academe_Specimen, 0, 1, 1, 1)
        self.lineEdit_Poss_Academe_Experiment = QtWidgets.QLineEdit(self.page)
        self.lineEdit_Poss_Academe_Experiment.setObjectName("lineEdit_Poss_Academe_Experiment")
        self.gridLayout_5.addWidget(self.lineEdit_Poss_Academe_Experiment, 0, 4, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.page)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.page)
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 0, 3, 1, 1)
        self.lineEdit_Poss_Academe_Artifact = QtWidgets.QLineEdit(self.page)
        self.lineEdit_Poss_Academe_Artifact.setObjectName("lineEdit_Poss_Academe_Artifact")
        self.gridLayout_5.addWidget(self.lineEdit_Poss_Academe_Artifact, 2, 1, 1, 1)
        self.lineEdit_Poss_Academe_Enigma = QtWidgets.QLineEdit(self.page)
        self.lineEdit_Poss_Academe_Enigma.setObjectName("lineEdit_Poss_Academe_Enigma")
        self.gridLayout_5.addWidget(self.lineEdit_Poss_Academe_Enigma, 2, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 2, 2, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 558, 69))
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_Poss_Bohemia_SkyStory = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_Poss_Bohemia_SkyStory.setObjectName("lineEdit_Poss_Bohemia_SkyStory")
        self.gridLayout_6.addWidget(self.lineEdit_Poss_Bohemia_SkyStory, 0, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.page_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 0, 4, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.page_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 4, 4, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.page_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.page_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 4, 0, 1, 1)
        self.lineEdit_Poss_Bohemia_Vision = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_Poss_Bohemia_Vision.setObjectName("lineEdit_Poss_Bohemia_Vision")
        self.gridLayout_6.addWidget(self.lineEdit_Poss_Bohemia_Vision, 4, 2, 1, 1)
        self.lineEdit_Poss_Bohemia_Moment = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_Poss_Bohemia_Moment.setObjectName("lineEdit_Poss_Bohemia_Moment")
        self.gridLayout_6.addWidget(self.lineEdit_Poss_Bohemia_Moment, 0, 5, 1, 1)
        self.lineEdit_Poss_Bohemia_Treasure = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_Poss_Bohemia_Treasure.setObjectName("lineEdit_Poss_Bohemia_Treasure")
        self.gridLayout_6.addWidget(self.lineEdit_Poss_Bohemia_Treasure, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 4, 3, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 558, 69))
        self.page_3.setObjectName("page_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_38 = QtWidgets.QLabel(self.page_3)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 1, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.page_3)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 0, 3, 1, 1)
        self.lineEdit_Poss_Estab_Gossip = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_Poss_Estab_Gossip.setObjectName("lineEdit_Poss_Estab_Gossip")
        self.gridLayout_7.addWidget(self.lineEdit_Poss_Estab_Gossip, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.page_3)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 0, 0, 1, 1)
        self.lineEdit_Poss_Estab_Benefactor = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_Poss_Estab_Benefactor.setObjectName("lineEdit_Poss_Estab_Benefactor")
        self.gridLayout_7.addWidget(self.lineEdit_Poss_Estab_Benefactor, 0, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.page_3)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 1, 3, 1, 1)
        self.lineEdit_Poss_Estab_Permit = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_Poss_Estab_Permit.setObjectName("lineEdit_Poss_Estab_Permit")
        self.gridLayout_7.addWidget(self.lineEdit_Poss_Estab_Permit, 1, 1, 1, 1)
        self.lineEdit_Poss_Estab_Dispensation = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_Poss_Estab_Dispensation.setObjectName("lineEdit_Poss_Estab_Dispensation")
        self.gridLayout_7.addWidget(self.lineEdit_Poss_Estab_Dispensation, 1, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 1, 2, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 558, 69))
        self.page_4.setObjectName("page_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_41 = QtWidgets.QLabel(self.page_4)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.page_4)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 1, 3, 1, 1)
        self.lineEdit_Poss_Villainy_Tale = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_Poss_Villainy_Tale.setObjectName("lineEdit_Poss_Villainy_Tale")
        self.gridLayout_8.addWidget(self.lineEdit_Poss_Villainy_Tale, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.page_4)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 0, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.page_4)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 1, 0, 1, 1)
        self.lineEdit_Poss_Villainy_Chart = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_Poss_Villainy_Chart.setObjectName("lineEdit_Poss_Villainy_Chart")
        self.gridLayout_8.addWidget(self.lineEdit_Poss_Villainy_Chart, 0, 4, 1, 1)
        self.lineEdit_Poss_Villainy_Secret = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_Poss_Villainy_Secret.setObjectName("lineEdit_Poss_Villainy_Secret")
        self.gridLayout_8.addWidget(self.lineEdit_Poss_Villainy_Secret, 1, 1, 1, 1)
        self.lineEdit_Poss_Villainy_Promise = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_Poss_Villainy_Promise.setObjectName("lineEdit_Poss_Villainy_Promise")
        self.gridLayout_8.addWidget(self.lineEdit_Poss_Villainy_Promise, 1, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 1, 2, 1, 1)
        self.toolBox.addItem(self.page_4, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 558, 90))
        self.page_6.setObjectName("page_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_46 = QtWidgets.QLabel(self.page_6)
        self.label_46.setObjectName("label_46")
        self.gridLayout_9.addWidget(self.label_46, 0, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.page_6)
        self.label_45.setObjectName("label_45")
        self.gridLayout_9.addWidget(self.label_45, 0, 0, 1, 1)
        self.lineEdit_Poss_Gratitude_Tacketies = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_Poss_Gratitude_Tacketies.setObjectName("lineEdit_Poss_Gratitude_Tacketies")
        self.gridLayout_9.addWidget(self.lineEdit_Poss_Gratitude_Tacketies, 0, 4, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.page_6)
        self.label_47.setObjectName("label_47")
        self.gridLayout_9.addWidget(self.label_47, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem9, 1, 2, 1, 1)
        self.lineEdit_Poss_Gratitudes_Windward = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_Poss_Gratitudes_Windward.setObjectName("lineEdit_Poss_Gratitudes_Windward")
        self.gridLayout_9.addWidget(self.lineEdit_Poss_Gratitudes_Windward, 0, 1, 1, 1)
        self.lineEdit_Poss_Gratitude_Ministry = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_Poss_Gratitude_Ministry.setObjectName("lineEdit_Poss_Gratitude_Ministry")
        self.gridLayout_9.addWidget(self.lineEdit_Poss_Gratitude_Ministry, 1, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.page_6)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 1, 3, 1, 1)
        self.lineEdit_Poss_Gratitude_NSL = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_Poss_Gratitude_NSL.setObjectName("lineEdit_Poss_Gratitude_NSL")
        self.gridLayout_9.addWidget(self.lineEdit_Poss_Gratitude_NSL, 1, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 0, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.page_6)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 2, 0, 1, 1)
        self.lineEdit_Poss_Gratitude_Embassy = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_Poss_Gratitude_Embassy.setObjectName("lineEdit_Poss_Gratitude_Embassy")
        self.gridLayout_9.addWidget(self.lineEdit_Poss_Gratitude_Embassy, 2, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 2, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.page_6)
        self.label_50.setObjectName("label_50")
        self.gridLayout_9.addWidget(self.label_50, 2, 3, 1, 1)
        self.lineEdit_Poss_Gratitude_Society = QtWidgets.QLineEdit(self.page_6)
        self.lineEdit_Poss_Gratitude_Society.setObjectName("lineEdit_Poss_Gratitude_Society")
        self.gridLayout_9.addWidget(self.lineEdit_Poss_Gratitude_Society, 2, 4, 1, 1)
        self.toolBox.addItem(self.page_6, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 558, 69))
        self.page_7.setObjectName("page_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_52 = QtWidgets.QLabel(self.page_7)
        self.label_52.setObjectName("label_52")
        self.gridLayout_10.addWidget(self.label_52, 0, 0, 1, 1)
        self.lineEdit_Poss_Misc_Guests = QtWidgets.QLineEdit(self.page_7)
        self.lineEdit_Poss_Misc_Guests.setObjectName("lineEdit_Poss_Misc_Guests")
        self.gridLayout_10.addWidget(self.lineEdit_Poss_Misc_Guests, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem12, 0, 2, 1, 1)
        self.toolBox.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 558, 150))
        self.page_8.setObjectName("page_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_Poss_Reports = QtWidgets.QCheckBox(self.page_8)
        self.checkBox_Poss_Reports.setObjectName("checkBox_Poss_Reports")
        self.verticalLayout_3.addWidget(self.checkBox_Poss_Reports)
        self.label_51 = QtWidgets.QLabel(self.page_8)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_3.addWidget(self.label_51)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem13)
        self.toolBox.addItem(self.page_8, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 558, 69))
        self.page_10.setObjectName("page_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.checkBox_Poss_Heirloom_Secret = QtWidgets.QCheckBox(self.page_10)
        self.checkBox_Poss_Heirloom_Secret.setObjectName("checkBox_Poss_Heirloom_Secret")
        self.gridLayout_11.addWidget(self.checkBox_Poss_Heirloom_Secret, 1, 1, 1, 1)
        self.checkBox_Poss_Heirloom_Wealth = QtWidgets.QCheckBox(self.page_10)
        self.checkBox_Poss_Heirloom_Wealth.setObjectName("checkBox_Poss_Heirloom_Wealth")
        self.gridLayout_11.addWidget(self.checkBox_Poss_Heirloom_Wealth, 0, 0, 1, 1)
        self.checkBox_Poss_Heirloom_Cup = QtWidgets.QCheckBox(self.page_10)
        self.checkBox_Poss_Heirloom_Cup.setObjectName("checkBox_Poss_Heirloom_Cup")
        self.gridLayout_11.addWidget(self.checkBox_Poss_Heirloom_Cup, 0, 1, 1, 1)
        self.checkBox_Poss_Heirloom_Song = QtWidgets.QCheckBox(self.page_10)
        self.checkBox_Poss_Heirloom_Song.setObjectName("checkBox_Poss_Heirloom_Song")
        self.gridLayout_11.addWidget(self.checkBox_Poss_Heirloom_Song, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_10, "")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 541, 109))
        self.page_9.setObjectName("page_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_53 = QtWidgets.QLabel(self.page_9)
        self.label_53.setObjectName("label_53")
        self.gridLayout_12.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.page_9)
        self.label_54.setObjectName("label_54")
        self.gridLayout_12.addWidget(self.label_54, 1, 0, 1, 1)
        self.lineEdit_Poss_ReachMisc_Shard = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_Poss_ReachMisc_Shard.setObjectName("lineEdit_Poss_ReachMisc_Shard")
        self.gridLayout_12.addWidget(self.lineEdit_Poss_ReachMisc_Shard, 1, 4, 1, 1)
        self.lineEdit_Poss_ReachMisc_Circus = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_Poss_ReachMisc_Circus.setObjectName("lineEdit_Poss_ReachMisc_Circus")
        self.gridLayout_12.addWidget(self.lineEdit_Poss_ReachMisc_Circus, 1, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.page_9)
        self.label_55.setObjectName("label_55")
        self.gridLayout_12.addWidget(self.label_55, 1, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.page_9)
        self.label_56.setObjectName("label_56")
        self.gridLayout_12.addWidget(self.label_56, 0, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem14, 1, 2, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.page_9)
        self.label_67.setObjectName("label_67")
        self.gridLayout_12.addWidget(self.label_67, 2, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem15, 2, 2, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.page_9)
        self.label_68.setObjectName("label_68")
        self.gridLayout_12.addWidget(self.label_68, 2, 3, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.page_9)
        self.label_69.setObjectName("label_69")
        self.gridLayout_12.addWidget(self.label_69, 3, 0, 1, 1)
        self.lineEdit_Poss_ReachMisc_TacketyPlate = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_Poss_ReachMisc_TacketyPlate.setObjectName("lineEdit_Poss_ReachMisc_TacketyPlate")
        self.gridLayout_12.addWidget(self.lineEdit_Poss_ReachMisc_TacketyPlate, 2, 4, 1, 1)
        self.lineEdit_Poss_ReachMisc_StovepipePlate = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit_Poss_ReachMisc_StovepipePlate.setObjectName("lineEdit_Poss_ReachMisc_StovepipePlate")
        self.gridLayout_12.addWidget(self.lineEdit_Poss_ReachMisc_StovepipePlate, 3, 1, 1, 1)
        self.toolBox.addItem(self.page_9, "")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setGeometry(QtCore.QRect(0, 0, 558, 69))
        self.page_11.setObjectName("page_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_11)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_65 = QtWidgets.QLabel(self.page_11)
        self.label_65.setObjectName("label_65")
        self.gridLayout_14.addWidget(self.label_65, 0, 3, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.page_11)
        self.label_66.setObjectName("label_66")
        self.gridLayout_14.addWidget(self.label_66, 0, 0, 1, 1)
        self.lineEdit_Poss_AlbionMisc_Invites = QtWidgets.QLineEdit(self.page_11)
        self.lineEdit_Poss_AlbionMisc_Invites.setObjectName("lineEdit_Poss_AlbionMisc_Invites")
        self.gridLayout_14.addWidget(self.lineEdit_Poss_AlbionMisc_Invites, 0, 4, 1, 1)
        self.lineEdit_Poss_AlbionMisc_Mods = QtWidgets.QLineEdit(self.page_11)
        self.lineEdit_Poss_AlbionMisc_Mods.setObjectName("lineEdit_Poss_AlbionMisc_Mods")
        self.gridLayout_14.addWidget(self.lineEdit_Poss_AlbionMisc_Mods, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem16, 0, 2, 1, 1)
        self.toolBox.addItem(self.page_11, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 558, 258))
        self.page_5.setObjectName("page_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_61 = QtWidgets.QLabel(self.page_5)
        self.label_61.setObjectName("label_61")
        self.gridLayout_13.addWidget(self.label_61, 4, 4, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.page_5)
        self.label_62.setObjectName("label_62")
        self.gridLayout_13.addWidget(self.label_62, 9, 4, 1, 1)
        self.lineEdit_Poss_EleuMisc_Golden = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_Golden.setObjectName("lineEdit_Poss_EleuMisc_Golden")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_Golden, 9, 5, 1, 1)
        self.lineEdit_Poss_EleuMisc_Soft = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_Soft.setObjectName("lineEdit_Poss_EleuMisc_Soft")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_Soft, 4, 5, 1, 1)
        self.lineEdit_Poss_EleuMisc_Red = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_Red.setObjectName("lineEdit_Poss_EleuMisc_Red")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_Red, 2, 5, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.page_5)
        self.label_59.setObjectName("label_59")
        self.gridLayout_13.addWidget(self.label_59, 2, 4, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.page_5)
        self.label_57.setObjectName("label_57")
        self.gridLayout_13.addWidget(self.label_57, 0, 4, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.page_5)
        self.label_60.setObjectName("label_60")
        self.gridLayout_13.addWidget(self.label_60, 1, 4, 1, 1)
        self.lineEdit_Poss_EleuMisc_Green = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_Green.setObjectName("lineEdit_Poss_EleuMisc_Green")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_Green, 1, 5, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.page_5)
        self.label_58.setObjectName("label_58")
        self.gridLayout_13.addWidget(self.label_58, 3, 4, 1, 1)
        self.lineEdit_Poss_EleuMisc_Blue = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_Blue.setObjectName("lineEdit_Poss_EleuMisc_Blue")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_Blue, 3, 5, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.page_5)
        self.label_71.setObjectName("label_71")
        self.gridLayout_13.addWidget(self.label_71, 0, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.page_5)
        self.label_72.setObjectName("label_72")
        self.gridLayout_13.addWidget(self.label_72, 1, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.page_5)
        self.label_73.setObjectName("label_73")
        self.gridLayout_13.addWidget(self.label_73, 2, 1, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.page_5)
        self.label_74.setObjectName("label_74")
        self.gridLayout_13.addWidget(self.label_74, 3, 1, 1, 1)
        self.lineEdit_Poss_EleuMisc_EmpyreanPlate = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_EmpyreanPlate.setObjectName("lineEdit_Poss_EleuMisc_EmpyreanPlate")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_EmpyreanPlate, 1, 2, 1, 1)
        self.lineEdit_Poss_EleuMisc_DouserPlate = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_DouserPlate.setObjectName("lineEdit_Poss_EleuMisc_DouserPlate")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_DouserPlate, 3, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.page_5)
        self.label_64.setObjectName("label_64")
        self.gridLayout_13.addWidget(self.label_64, 4, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.page_5)
        self.label_63.setObjectName("label_63")
        self.gridLayout_13.addWidget(self.label_63, 9, 1, 1, 1)
        self.lineEdit_Poss_EleuMisc_Mystery = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_Mystery.setObjectName("lineEdit_Poss_EleuMisc_Mystery")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_Mystery, 9, 2, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.page_5)
        self.label_70.setObjectName("label_70")
        self.gridLayout_13.addWidget(self.label_70, 11, 1, 1, 1)
        self.lineEdit_Poss_EleuMisc_Scrap = QtWidgets.QLineEdit(self.page_5)
        self.lineEdit_Poss_EleuMisc_Scrap.setObjectName("lineEdit_Poss_EleuMisc_Scrap")
        self.gridLayout_13.addWidget(self.lineEdit_Poss_EleuMisc_Scrap, 11, 2, 1, 1)
        self.toolBox.addItem(self.page_5, "")
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_12)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_75 = QtWidgets.QLabel(self.page_12)
        self.label_75.setObjectName("label_75")
        self.gridLayout_15.addWidget(self.label_75, 1, 0, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.page_12)
        self.label_77.setObjectName("label_77")
        self.gridLayout_15.addWidget(self.label_77, 3, 0, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.page_12)
        self.label_78.setObjectName("label_78")
        self.gridLayout_15.addWidget(self.label_78, 0, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.page_12)
        self.label_76.setObjectName("label_76")
        self.gridLayout_15.addWidget(self.label_76, 2, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.page_12)
        self.label_80.setObjectName("label_80")
        self.gridLayout_15.addWidget(self.label_80, 1, 3, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.page_12)
        self.label_79.setObjectName("label_79")
        self.gridLayout_15.addWidget(self.label_79, 0, 3, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.page_12)
        self.label_81.setObjectName("label_81")
        self.gridLayout_15.addWidget(self.label_81, 2, 3, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.page_12)
        self.label_83.setObjectName("label_83")
        self.gridLayout_15.addWidget(self.label_83, 4, 3, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.page_12)
        self.label_82.setObjectName("label_82")
        self.gridLayout_15.addWidget(self.label_82, 3, 3, 1, 1)
        self.lineEdit_Poss_TBKMisc_Indulgence = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Indulgence.setObjectName("lineEdit_Poss_TBKMisc_Indulgence")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Indulgence, 0, 1, 1, 1)
        self.lineEdit_Poss_TBKMisc_Volumes = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Volumes.setObjectName("lineEdit_Poss_TBKMisc_Volumes")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Volumes, 0, 4, 1, 1)
        self.lineEdit_Poss_TBKMisc_Roses = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Roses.setObjectName("lineEdit_Poss_TBKMisc_Roses")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Roses, 1, 1, 1, 1)
        self.lineEdit_Poss_TBKMisc_Flowers = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Flowers.setObjectName("lineEdit_Poss_TBKMisc_Flowers")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Flowers, 3, 1, 1, 1)
        self.lineEdit_Poss_TBKMisc_Salt = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Salt.setObjectName("lineEdit_Poss_TBKMisc_Salt")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Salt, 2, 1, 1, 1)
        self.lineEdit_Poss_TBKMisc_Verdance = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Verdance.setObjectName("lineEdit_Poss_TBKMisc_Verdance")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Verdance, 2, 4, 1, 1)
        self.lineEdit_Poss_TBKMisc_Hourglass = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Hourglass.setObjectName("lineEdit_Poss_TBKMisc_Hourglass")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Hourglass, 3, 4, 1, 1)
        self.lineEdit_Poss_TBKMisc_Incarnadine = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Incarnadine.setObjectName("lineEdit_Poss_TBKMisc_Incarnadine")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Incarnadine, 1, 4, 1, 1)
        self.lineEdit_Poss_TBKMisc_Dominion = QtWidgets.QLineEdit(self.page_12)
        self.lineEdit_Poss_TBKMisc_Dominion.setObjectName("lineEdit_Poss_TBKMisc_Dominion")
        self.gridLayout_15.addWidget(self.lineEdit_Poss_TBKMisc_Dominion, 4, 4, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem17, 3, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem18, 2, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem19, 1, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem20, 0, 2, 1, 1)
        self.toolBox.addItem(self.page_12, "")
        self.gridLayout_4.addWidget(self.toolBox, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem21, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sunless Skies Save Editor"))
        self.pushButton_Open.setText(_translate("MainWindow", "Open"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save"))
        self.pushButton_About.setText(_translate("MainWindow", "About"))
        self.label_LoadedFile.setText(_translate("MainWindow", "Loaded savefile:"))
        self.label_LoadedFileName.setText(_translate("MainWindow", "None"))
        self.label_9.setText(_translate("MainWindow", "="))
        self.label_18.setText(_translate("MainWindow", "+"))
        self.label_15.setText(_translate("MainWindow", "="))
        self.label_20.setText(_translate("MainWindow", "+"))
        self.label_Terror.setText(_translate("MainWindow", "Terror:"))
        self.label_Sovereigns.setText(_translate("MainWindow", "Sovereigns:"))
        self.label_19.setText(_translate("MainWindow", "+"))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.label_Crew.setText(_translate("MainWindow", "Crew:"))
        self.label_Date.setText(_translate("MainWindow", "Date"))
        self.label_SecretComp.setText(_translate("MainWindow", "<html><head/><body><p>Secret<br>Compartments:</p></body></html>"))
        self.label_Hull.setText(_translate("MainWindow", "Hull:"))
        self.label_Veils.setText(_translate("MainWindow", "Veils:"))
        self.label_Hold.setText(_translate("MainWindow", "Hold:"))
        self.label_Hearts.setText(_translate("MainWindow", "Hearts:"))
        self.label_Condition.setText(_translate("MainWindow", "Condition:"))
        self.label_5.setText(_translate("MainWindow", "Effective Level Modifier"))
        self.label_Exp.setText(_translate("MainWindow", "Experience:"))
        self.label_Mirrors.setText(_translate("MainWindow", "Mirrors:"))
        self.label_Iron.setText(_translate("MainWindow", "Iron:"))
        self.label_CharPoints.setText(_translate("MainWindow", "Character Points:"))
        self.label_4.setText(_translate("MainWindow", "Level"))
        self.label_CharLevel.setText(_translate("MainWindow", "Charactrer Level:"))
        self.label_23.setText(_translate("MainWindow", "+"))
        self.label_24.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "+"))
        self.label_13.setText(_translate("MainWindow", "="))
        self.label_7.setText(_translate("MainWindow", "="))
        self.label_12.setText(_translate("MainWindow", "="))
        self.label_8.setText(_translate("MainWindow", "="))
        self.label_17.setText(_translate("MainWindow", "="))
        self.label_3.setText(_translate("MainWindow", "Effective Level"))
        self.label_2.setText(_translate("MainWindow", "="))
        self.label.setText(_translate("MainWindow", "="))
        self.label_22.setText(_translate("MainWindow", "="))
        self.label_6.setText(_translate("MainWindow", "="))
        self.label_11.setText(_translate("MainWindow", "="))
        self.label_16.setText(_translate("MainWindow", "="))
        self.label_10.setText(_translate("MainWindow", "="))
        self.label_14.setText(_translate("MainWindow", "="))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stats), _translate("MainWindow", "Stats"))
        self.label_26.setText(_translate("MainWindow", "Current Location"))
        self.label_27.setText(_translate("MainWindow", "Fog of War Disabled"))
        self.checkBox_FoW_Albion.setText(_translate("MainWindow", "Albion"))
        self.checkBox_FoW_Reach.setText(_translate("MainWindow", "The Reach"))
        self.checkBox_FoW_Eleutheria.setText(_translate("MainWindow", "Eleutheria"))
        self.checkBox_FoW_BlueKingdom.setText(_translate("MainWindow", "The Blue  Kingdom"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Checked</span>: Fog of War removed</p><p><span style=\" font-weight:600;\">Partially Checked: </span>Some parts of Fog of War removed (by natural exploration) </p><p><span style=\" font-weight:600;\">Unchecked: </span>Fog of War covers the whole map</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Map"))
        self.label_31.setText(_translate("MainWindow", "Otherwordly Artifact"))
        self.label_32.setText(_translate("MainWindow", "Searing Enigma"))
        self.label_30.setText(_translate("MainWindow", "Uncanny Specimen"))
        self.label_29.setText(_translate("MainWindow", "Condemnced Experiment"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Academe"))
        self.label_35.setText(_translate("MainWindow", "Moment of Inspiration"))
        self.label_36.setText(_translate("MainWindow", "Captivating Treasure"))
        self.label_33.setText(_translate("MainWindow", "Sky-Story"))
        self.label_34.setText(_translate("MainWindow", "Vision of the Heavens"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Bohemia"))
        self.label_38.setText(_translate("MainWindow", "Ministry-Stamped Permit"))
        self.label_37.setText(_translate("MainWindow", "Cryptic Benefactor"))
        self.label_39.setText(_translate("MainWindow", "Salon-Stewed Gossip"))
        self.label_40.setText(_translate("MainWindow", "Royal Dispensation"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Establishment"))
        self.label_41.setText(_translate("MainWindow", "Tale of Terror"))
        self.label_42.setText(_translate("MainWindow", "Crimson Promise"))
        self.label_44.setText(_translate("MainWindow", "Unlicensed Chart"))
        self.label_43.setText(_translate("MainWindow", "Savage Secret"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Villainy"))
        self.label_46.setText(_translate("MainWindow", "The Tacketies\' Gratitude"))
        self.label_45.setText(_translate("MainWindow", "The Windward Company\'s Gratitude"))
        self.label_47.setText(_translate("MainWindow", "The Ministry\'s Gratitude"))
        self.label_48.setText(_translate("MainWindow", "The New Street Line\'s Gratitude"))
        self.label_49.setText(_translate("MainWindow", "The Gratitude of The Embassy of Albion"))
        self.label_50.setText(_translate("MainWindow", "The Royal Society\'s Gratitude"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", "Gratitudes"))
        self.label_52.setText(_translate("MainWindow", "Captive Guests"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("MainWindow", "Miscellaneous"))
        self.checkBox_Poss_Reports.setText(_translate("MainWindow", "Port Reports"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Checked:</span> You have one of each Port Report</p><p><span style=\" font-weight:600;\">Partially Checked: </span>You have some Port Reports</p><p><span style=\" font-weight:600;\">Unchecked: </span>You have no Port Reports</p></body></html>"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_8), _translate("MainWindow", "Port Reports"))
        self.checkBox_Poss_Heirloom_Secret.setText(_translate("MainWindow", "Heirloom: a Terrible Secret"))
        self.checkBox_Poss_Heirloom_Wealth.setText(_translate("MainWindow", "Heirloom: A Token of Vast Wealth"))
        self.checkBox_Poss_Heirloom_Cup.setText(_translate("MainWindow", "Heirloom: the Martyr-King\'s Cup"))
        self.checkBox_Poss_Heirloom_Song.setText(_translate("MainWindow", "Heirloom: The Song of the Sky"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_10), _translate("MainWindow", "Heirlooms"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Reach: Polmear and Plenty\'s</span></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "Tickets to the Circus"))
        self.label_55.setText(_translate("MainWindow", "Ambiguous Shard"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Reach: Lustrum</span></p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Reach: Port Prosper</span></p></body></html>"))
        self.label_68.setText(_translate("MainWindow", "Mangled Tackety Nameplate"))
        self.label_69.setText(_translate("MainWindow", "Charred Stovepipe Nameplate"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_9), _translate("MainWindow", "Reach: Miscellaneous"))
        self.label_65.setText(_translate("MainWindow", "Invitation to Perdurance"))
        self.label_66.setText(_translate("MainWindow", "Experimental Modifications"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_11), _translate("MainWindow", "Albion: Miscellaneous"))
        self.label_61.setText(_translate("MainWindow", "Chunks of Soft Amber"))
        self.label_62.setText(_translate("MainWindow", "Chunks of Golden Amber"))
        self.label_59.setText(_translate("MainWindow", "Chunks of Red Amber"))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Eleutheria: House of Rods and Chains</span></p></body></html>"))
        self.label_60.setText(_translate("MainWindow", "Chunks of Green Amber"))
        self.label_58.setText(_translate("MainWindow", "Chunks of Blue Amber"))
        self.label_71.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Eleutheria: Winter\'s Reside</span></p></body></html>"))
        self.label_72.setText(_translate("MainWindow", "Charred Empyrean Nameplate"))
        self.label_73.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Eleutheria: Eagle\'s Empyrean</span></p></body></html>"))
        self.label_74.setText(_translate("MainWindow", "Plaque from a Douser Engine"))
        self.label_64.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Miscellaneous</span></p></body></html>"))
        self.label_63.setText(_translate("MainWindow", "Eleutherian Mystery"))
        self.label_70.setText(_translate("MainWindow", "Scrap of Ancient Knowledge"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Eleutheria: Miscellaneous"))
        self.label_75.setText(_translate("MainWindow", "Testament of Roses"))
        self.label_77.setText(_translate("MainWindow", "Testament of Flowers"))
        self.label_78.setText(_translate("MainWindow", "Indulgence"))
        self.label_76.setText(_translate("MainWindow", "Testament of Salt"))
        self.label_80.setText(_translate("MainWindow", "Aspect of Incarnadine"))
        self.label_79.setText(_translate("MainWindow", "Volumes of Notes on the Blue Kingdom"))
        self.label_81.setText(_translate("MainWindow", "Aspect of Verdance"))
        self.label_83.setText(_translate("MainWindow", "Aspect of Dominion"))
        self.label_82.setText(_translate("MainWindow", "Aspect of the Hourglass"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_12), _translate("MainWindow", "The Blue Kingdom: Miscellaneous"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Possessions"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
