# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sunless_skies.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.horizontalLayout_3.addWidget(self.pushButton_Open)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_3.addWidget(self.pushButton_Save)
        self.pushButton_About = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_About.setObjectName("pushButton_About")
        self.horizontalLayout_3.addWidget(self.pushButton_About)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_LoadedFile = QtWidgets.QLabel(self.centralwidget)
        self.label_LoadedFile.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_LoadedFile.setObjectName("label_LoadedFile")
        self.horizontalLayout_2.addWidget(self.label_LoadedFile)
        self.label_LoadedFileName = QtWidgets.QLabel(self.centralwidget)
        self.label_LoadedFileName.setObjectName("label_LoadedFileName")
        self.horizontalLayout_2.addWidget(self.label_LoadedFileName)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_stats = QtWidgets.QWidget()
        self.tab_stats.setObjectName("tab_stats")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_stats)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_Modifier_Iron = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Iron.setObjectName("lineEdit_Modifier_Iron")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Iron, 10, 5, 1, 1)
        self.label_Sovereigns = QtWidgets.QLabel(self.tab_stats)
        self.label_Sovereigns.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Sovereigns.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Sovereigns.setObjectName("label_Sovereigns")
        self.gridLayout_2.addWidget(self.label_Sovereigns, 1, 0, 1, 1)
        self.label_Crew = QtWidgets.QLabel(self.tab_stats)
        self.label_Crew.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Crew.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Crew.setObjectName("label_Crew")
        self.gridLayout_2.addWidget(self.label_Crew, 5, 0, 1, 1)
        self.label_Date = QtWidgets.QLabel(self.tab_stats)
        self.label_Date.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Date.setObjectName("label_Date")
        self.gridLayout_2.addWidget(self.label_Date, 6, 0, 1, 1)
        self.label_Hull = QtWidgets.QLabel(self.tab_stats)
        self.label_Hull.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hull.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hull.setObjectName("label_Hull")
        self.gridLayout_2.addWidget(self.label_Hull, 4, 0, 1, 1)
        self.label_Terror = QtWidgets.QLabel(self.tab_stats)
        self.label_Terror.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Terror.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Terror.setObjectName("label_Terror")
        self.gridLayout_2.addWidget(self.label_Terror, 3, 0, 1, 1)
        self.label_SecretComp = QtWidgets.QLabel(self.tab_stats)
        self.label_SecretComp.setMaximumSize(QtCore.QSize(110, 40))
        self.label_SecretComp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_SecretComp.setObjectName("label_SecretComp")
        self.gridLayout_2.addWidget(self.label_SecretComp, 16, 0, 1, 1)
        self.label_Hold = QtWidgets.QLabel(self.tab_stats)
        self.label_Hold.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hold.setObjectName("label_Hold")
        self.gridLayout_2.addWidget(self.label_Hold, 7, 0, 1, 1)
        self.label_Condition = QtWidgets.QLabel(self.tab_stats)
        self.label_Condition.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Condition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Condition.setObjectName("label_Condition")
        self.gridLayout_2.addWidget(self.label_Condition, 17, 0, 1, 1)
        self.label_Veils = QtWidgets.QLabel(self.tab_stats)
        self.label_Veils.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Veils.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Veils.setObjectName("label_Veils")
        self.gridLayout_2.addWidget(self.label_Veils, 9, 0, 1, 1)
        self.label_Iron = QtWidgets.QLabel(self.tab_stats)
        self.label_Iron.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Iron.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Iron.setObjectName("label_Iron")
        self.gridLayout_2.addWidget(self.label_Iron, 10, 0, 1, 1)
        self.label_Hearts = QtWidgets.QLabel(self.tab_stats)
        self.label_Hearts.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hearts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hearts.setObjectName("label_Hearts")
        self.gridLayout_2.addWidget(self.label_Hearts, 8, 0, 1, 1)
        self.label_Exp = QtWidgets.QLabel(self.tab_stats)
        self.label_Exp.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Exp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Exp.setObjectName("label_Exp")
        self.gridLayout_2.addWidget(self.label_Exp, 15, 0, 1, 1)
        self.label_Mirrors = QtWidgets.QLabel(self.tab_stats)
        self.label_Mirrors.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Mirrors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Mirrors.setObjectName("label_Mirrors")
        self.gridLayout_2.addWidget(self.label_Mirrors, 11, 0, 1, 1)
        self.label_CharLevel = QtWidgets.QLabel(self.tab_stats)
        self.label_CharLevel.setMaximumSize(QtCore.QSize(110, 20))
        self.label_CharLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CharLevel.setObjectName("label_CharLevel")
        self.gridLayout_2.addWidget(self.label_CharLevel, 12, 0, 1, 1)
        self.label_CharPoints = QtWidgets.QLabel(self.tab_stats)
        self.label_CharPoints.setMaximumSize(QtCore.QSize(110, 20))
        self.label_CharPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CharPoints.setObjectName("label_CharPoints")
        self.gridLayout_2.addWidget(self.label_CharPoints, 13, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_stats)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 5, 1, 1)
        self.lineEdit_Modifier_Hold = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Hold.setObjectName("lineEdit_Modifier_Hold")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Hold, 7, 5, 1, 1)
        self.lineEdit_Lvl_Sovereigns = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Sovereigns.setObjectName("lineEdit_Lvl_Sovereigns")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Sovereigns, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_stats)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        self.lineEdit_Lvl_CharLvl = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_CharLvl.setObjectName("lineEdit_Lvl_CharLvl")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_CharLvl, 12, 3, 1, 1)
        self.lineEdit_Modifier_Mirrors = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Mirrors.setObjectName("lineEdit_Modifier_Mirrors")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Mirrors, 11, 5, 1, 1)
        self.lineEdit_Lvl_Hull = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Hull.setObjectName("lineEdit_Lvl_Hull")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Hull, 4, 3, 1, 1)
        self.lineEdit_Lvl_Veils = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Veils.setObjectName("lineEdit_Lvl_Veils")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Veils, 9, 3, 1, 1)
        self.lineEdit_Lvl_Date = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Date.setObjectName("lineEdit_Lvl_Date")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Date, 6, 3, 1, 1)
        self.lineEdit_Lvl_SecretComp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_SecretComp.setObjectName("lineEdit_Lvl_SecretComp")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_SecretComp, 16, 3, 1, 1)
        self.lineEdit_Lvl_Condition = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Condition.setObjectName("lineEdit_Lvl_Condition")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Condition, 17, 3, 1, 1)
        self.lineEdit_Lvl_Exp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Exp.setObjectName("lineEdit_Lvl_Exp")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Exp, 15, 3, 1, 1)
        self.lineEdit_Lvl_CharPts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_CharPts.setObjectName("lineEdit_Lvl_CharPts")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_CharPts, 13, 3, 1, 1)
        self.lineEdit_Lvl_Iron = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Iron.setObjectName("lineEdit_Lvl_Iron")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Iron, 10, 3, 1, 1)
        self.lineEdit_Lvl_Mirrors = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Mirrors.setObjectName("lineEdit_Lvl_Mirrors")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Mirrors, 11, 3, 1, 1)
        self.lineEdit_Lvl_Hearts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Hearts.setObjectName("lineEdit_Lvl_Hearts")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Hearts, 8, 3, 1, 1)
        self.lineEdit_Lvl_Crew = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Crew.setObjectName("lineEdit_Lvl_Crew")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Crew, 5, 3, 1, 1)
        self.lineEdit_Modifier_Hearts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Hearts.setObjectName("lineEdit_Modifier_Hearts")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Hearts, 8, 5, 1, 1)
        self.lineEdit_Lvl_Terror = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Terror.setObjectName("lineEdit_Lvl_Terror")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Terror, 3, 3, 1, 1)
        self.lineEdit_Modifier_Veils = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Veils.setObjectName("lineEdit_Modifier_Veils")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Veils, 9, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_stats)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 8, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_stats)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 10, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_stats)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_stats)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 11, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_stats)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_stats)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 11, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_stats)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 15, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_stats)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_stats)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 9, 6, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_stats)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 13, 6, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_stats)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 10, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_stats)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 7, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_stats)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 8, 6, 1, 1)
        self.lineEdit_Effective_Sovereigns = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Sovereigns.setReadOnly(True)
        self.lineEdit_Effective_Sovereigns.setObjectName("lineEdit_Effective_Sovereigns")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Sovereigns, 1, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_stats)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_stats)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 6, 1, 1)
        self.lineEdit_Effective_Crew = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Crew.setReadOnly(True)
        self.lineEdit_Effective_Crew.setObjectName("lineEdit_Effective_Crew")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Crew, 5, 7, 1, 1)
        self.lineEdit_Effective_Terror = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Terror.setReadOnly(True)
        self.lineEdit_Effective_Terror.setObjectName("lineEdit_Effective_Terror")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Terror, 3, 7, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_stats)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 16, 6, 1, 1)
        self.lineEdit_Effective_Date = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Date.setReadOnly(True)
        self.lineEdit_Effective_Date.setObjectName("lineEdit_Effective_Date")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Date, 6, 7, 1, 1)
        self.lineEdit_Effective_Hold = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Hold.setReadOnly(True)
        self.lineEdit_Effective_Hold.setObjectName("lineEdit_Effective_Hold")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Hold, 7, 7, 1, 1)
        self.lineEdit_Effective_Hull = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Hull.setReadOnly(True)
        self.lineEdit_Effective_Hull.setObjectName("lineEdit_Effective_Hull")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Hull, 4, 7, 1, 1)
        self.lineEdit_Effective_Mirrors = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Mirrors.setReadOnly(True)
        self.lineEdit_Effective_Mirrors.setObjectName("lineEdit_Effective_Mirrors")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Mirrors, 11, 7, 1, 1)
        self.lineEdit_Effective_CharLvl = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_CharLvl.setReadOnly(True)
        self.lineEdit_Effective_CharLvl.setObjectName("lineEdit_Effective_CharLvl")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_CharLvl, 12, 7, 1, 1)
        self.lineEdit_Effective_Hearts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Hearts.setReadOnly(True)
        self.lineEdit_Effective_Hearts.setObjectName("lineEdit_Effective_Hearts")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Hearts, 8, 7, 1, 1)
        self.lineEdit_Effective_Veils = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Veils.setReadOnly(True)
        self.lineEdit_Effective_Veils.setObjectName("lineEdit_Effective_Veils")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Veils, 9, 7, 1, 1)
        self.lineEdit_Effective_Iron = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Iron.setReadOnly(True)
        self.lineEdit_Effective_Iron.setObjectName("lineEdit_Effective_Iron")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Iron, 10, 7, 1, 1)
        self.lineEdit_Effective_CharPts = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_CharPts.setReadOnly(True)
        self.lineEdit_Effective_CharPts.setObjectName("lineEdit_Effective_CharPts")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_CharPts, 13, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_stats)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 12, 6, 1, 1)
        self.lineEdit_Effective_Exp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Exp.setReadOnly(True)
        self.lineEdit_Effective_Exp.setObjectName("lineEdit_Effective_Exp")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Exp, 15, 7, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_stats)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_stats)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 6, 1, 1)
        self.lineEdit_Effective_Condition = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_Condition.setReadOnly(True)
        self.lineEdit_Effective_Condition.setObjectName("lineEdit_Effective_Condition")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_Condition, 17, 7, 1, 1)
        self.lineEdit_Effective_SecretComp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Effective_SecretComp.setReadOnly(True)
        self.lineEdit_Effective_SecretComp.setObjectName("lineEdit_Effective_SecretComp")
        self.gridLayout_2.addWidget(self.lineEdit_Effective_SecretComp, 16, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_stats)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 17, 6, 1, 1)
        self.lineEdit_Modifier_Hull = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_Hull.setObjectName("lineEdit_Modifier_Hull")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_Hull, 4, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_stats)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_stats)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 7, 4, 1, 1)
        self.lineEdit_Lvl_Hold = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Lvl_Hold.setObjectName("lineEdit_Lvl_Hold")
        self.gridLayout_2.addWidget(self.lineEdit_Lvl_Hold, 7, 3, 1, 1)
        self.lineEdit_Modifier_SecretComp = QtWidgets.QLineEdit(self.tab_stats)
        self.lineEdit_Modifier_SecretComp.setObjectName("lineEdit_Modifier_SecretComp")
        self.gridLayout_2.addWidget(self.lineEdit_Modifier_SecretComp, 16, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_stats)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 16, 4, 1, 1)
        self.tabWidget.addTab(self.tab_stats, "")
        self.tab_hold = QtWidgets.QWidget()
        self.tab_hold.setObjectName("tab_hold")
        self.tabWidget.addTab(self.tab_hold, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sunless Skies Save Editor"))
        self.pushButton_Open.setText(_translate("MainWindow", "Open"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save"))
        self.pushButton_About.setText(_translate("MainWindow", "About"))
        self.label_LoadedFile.setText(_translate("MainWindow", "Loaded savefile:"))
        self.label_LoadedFileName.setText(_translate("MainWindow", "None"))
        self.label_Sovereigns.setText(_translate("MainWindow", "Sovereigns:"))
        self.label_Crew.setText(_translate("MainWindow", "Crew:"))
        self.label_Date.setText(_translate("MainWindow", "Date"))
        self.label_Hull.setText(_translate("MainWindow", "Hull:"))
        self.label_Terror.setText(_translate("MainWindow", "Terror:"))
        self.label_SecretComp.setText(_translate("MainWindow", "<html><head/><body><p>Secret<br>Compartments:</p></body></html>"))
        self.label_Hold.setText(_translate("MainWindow", "Hold:"))
        self.label_Condition.setText(_translate("MainWindow", "Condition:"))
        self.label_Veils.setText(_translate("MainWindow", "Veils:"))
        self.label_Iron.setText(_translate("MainWindow", "Iron:"))
        self.label_Hearts.setText(_translate("MainWindow", "Hearts:"))
        self.label_Exp.setText(_translate("MainWindow", "Experience:"))
        self.label_Mirrors.setText(_translate("MainWindow", "Mirrors:"))
        self.label_CharLevel.setText(_translate("MainWindow", "Charactrer Level:"))
        self.label_CharPoints.setText(_translate("MainWindow", "Character Points:"))
        self.label_5.setText(_translate("MainWindow", "Effective Level Modifier"))
        self.label_4.setText(_translate("MainWindow", "Level"))
        self.label_18.setText(_translate("MainWindow", "+"))
        self.label_20.setText(_translate("MainWindow", "+"))
        self.label_19.setText(_translate("MainWindow", "+"))
        self.label_21.setText(_translate("MainWindow", "+"))
        self.label_15.setText(_translate("MainWindow", "="))
        self.label_9.setText(_translate("MainWindow", "="))
        self.label_13.setText(_translate("MainWindow", "="))
        self.label_17.setText(_translate("MainWindow", "="))
        self.label_7.setText(_translate("MainWindow", "="))
        self.label_12.setText(_translate("MainWindow", "="))
        self.label_8.setText(_translate("MainWindow", "="))
        self.label_2.setText(_translate("MainWindow", "="))
        self.label.setText(_translate("MainWindow", "="))
        self.label_3.setText(_translate("MainWindow", "Effective Level"))
        self.label_6.setText(_translate("MainWindow", "="))
        self.label_22.setText(_translate("MainWindow", "="))
        self.label_11.setText(_translate("MainWindow", "="))
        self.label_16.setText(_translate("MainWindow", "="))
        self.label_10.setText(_translate("MainWindow", "="))
        self.label_14.setText(_translate("MainWindow", "="))
        self.label_23.setText(_translate("MainWindow", "+"))
        self.label_24.setText(_translate("MainWindow", "+"))
        self.label_25.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stats), _translate("MainWindow", "Stats"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hold), _translate("MainWindow", "Hold"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
