# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sunless_skies.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.horizontalLayout_3.addWidget(self.pushButton_Open)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_3.addWidget(self.pushButton_Save)
        self.pushButton_About = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_About.setObjectName("pushButton_About")
        self.horizontalLayout_3.addWidget(self.pushButton_About)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_LoadedFile = QtWidgets.QLabel(self.centralwidget)
        self.label_LoadedFile.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_LoadedFile.setObjectName("label_LoadedFile")
        self.horizontalLayout_2.addWidget(self.label_LoadedFile)
        self.label_LoadedFileName = QtWidgets.QLabel(self.centralwidget)
        self.label_LoadedFileName.setObjectName("label_LoadedFileName")
        self.horizontalLayout_2.addWidget(self.label_LoadedFileName)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_stats = QtWidgets.QWidget()
        self.tab_stats.setObjectName("tab_stats")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_stats)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit_Sovereigns = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Sovereigns.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Sovereigns.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Sovereigns.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Sovereigns.setObjectName("plainTextEdit_Sovereigns")
        self.gridLayout_2.addWidget(self.plainTextEdit_Sovereigns, 1, 1, 1, 1)
        self.plainTextEdit_Hearts = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Hearts.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Hearts.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Hearts.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Hearts.setObjectName("plainTextEdit_Hearts")
        self.gridLayout_2.addWidget(self.plainTextEdit_Hearts, 1, 3, 1, 1)
        self.plainTextEdit_Terror = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Terror.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Terror.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Terror.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Terror.setObjectName("plainTextEdit_Terror")
        self.gridLayout_2.addWidget(self.plainTextEdit_Terror, 2, 1, 1, 1)
        self.plainTextEdit_Hull = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Hull.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Hull.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Hull.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Hull.setObjectName("plainTextEdit_Hull")
        self.gridLayout_2.addWidget(self.plainTextEdit_Hull, 3, 1, 1, 1)
        self.plainTextEdit_Crew = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Crew.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Crew.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Crew.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Crew.setObjectName("plainTextEdit_Crew")
        self.gridLayout_2.addWidget(self.plainTextEdit_Crew, 4, 1, 1, 1)
        self.plainTextEdit_Date = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Date.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Date.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Date.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Date.setObjectName("plainTextEdit_Date")
        self.gridLayout_2.addWidget(self.plainTextEdit_Date, 5, 1, 1, 1)
        self.plainTextEdit_Hold = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Hold.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Hold.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Hold.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Hold.setObjectName("plainTextEdit_Hold")
        self.gridLayout_2.addWidget(self.plainTextEdit_Hold, 6, 1, 1, 1)
        self.plainTextEdit_SecretComp = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_SecretComp.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_SecretComp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_SecretComp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_SecretComp.setObjectName("plainTextEdit_SecretComp")
        self.gridLayout_2.addWidget(self.plainTextEdit_SecretComp, 7, 1, 1, 1)
        self.plainTextEdit_Condition = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Condition.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Condition.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Condition.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Condition.setObjectName("plainTextEdit_Condition")
        self.gridLayout_2.addWidget(self.plainTextEdit_Condition, 8, 1, 1, 1)
        self.plainTextEdit_Veils = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Veils.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Veils.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Veils.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Veils.setObjectName("plainTextEdit_Veils")
        self.gridLayout_2.addWidget(self.plainTextEdit_Veils, 2, 3, 1, 1)
        self.plainTextEdit_Iron = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Iron.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Iron.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Iron.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Iron.setObjectName("plainTextEdit_Iron")
        self.gridLayout_2.addWidget(self.plainTextEdit_Iron, 3, 3, 1, 1)
        self.plainTextEdit_Mirrors = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Mirrors.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Mirrors.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Mirrors.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Mirrors.setObjectName("plainTextEdit_Mirrors")
        self.gridLayout_2.addWidget(self.plainTextEdit_Mirrors, 4, 3, 1, 1)
        self.plainTextEdit_CharLevel = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_CharLevel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_CharLevel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_CharLevel.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_CharLevel.setObjectName("plainTextEdit_CharLevel")
        self.gridLayout_2.addWidget(self.plainTextEdit_CharLevel, 5, 3, 1, 1)
        self.plainTextEdit_CharPoints = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_CharPoints.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_CharPoints.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_CharPoints.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_CharPoints.setObjectName("plainTextEdit_CharPoints")
        self.gridLayout_2.addWidget(self.plainTextEdit_CharPoints, 6, 3, 1, 1)
        self.plainTextEdit_Exp = QtWidgets.QPlainTextEdit(self.tab_stats)
        self.plainTextEdit_Exp.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_Exp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Exp.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_Exp.setObjectName("plainTextEdit_Exp")
        self.gridLayout_2.addWidget(self.plainTextEdit_Exp, 7, 3, 1, 1)
        self.label_Sovereigns = QtWidgets.QLabel(self.tab_stats)
        self.label_Sovereigns.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Sovereigns.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Sovereigns.setObjectName("label_Sovereigns")
        self.gridLayout_2.addWidget(self.label_Sovereigns, 1, 0, 1, 1)
        self.label_Terror = QtWidgets.QLabel(self.tab_stats)
        self.label_Terror.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Terror.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Terror.setObjectName("label_Terror")
        self.gridLayout_2.addWidget(self.label_Terror, 2, 0, 1, 1)
        self.label_Hull = QtWidgets.QLabel(self.tab_stats)
        self.label_Hull.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hull.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hull.setObjectName("label_Hull")
        self.gridLayout_2.addWidget(self.label_Hull, 3, 0, 1, 1)
        self.label_Crew = QtWidgets.QLabel(self.tab_stats)
        self.label_Crew.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Crew.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Crew.setObjectName("label_Crew")
        self.gridLayout_2.addWidget(self.label_Crew, 4, 0, 1, 1)
        self.label_Date = QtWidgets.QLabel(self.tab_stats)
        self.label_Date.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Date.setObjectName("label_Date")
        self.gridLayout_2.addWidget(self.label_Date, 5, 0, 1, 1)
        self.label_Hold = QtWidgets.QLabel(self.tab_stats)
        self.label_Hold.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hold.setObjectName("label_Hold")
        self.gridLayout_2.addWidget(self.label_Hold, 6, 0, 1, 1)
        self.label_SecretComp = QtWidgets.QLabel(self.tab_stats)
        self.label_SecretComp.setMaximumSize(QtCore.QSize(110, 40))
        self.label_SecretComp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_SecretComp.setObjectName("label_SecretComp")
        self.gridLayout_2.addWidget(self.label_SecretComp, 7, 0, 1, 1)
        self.label_Condition = QtWidgets.QLabel(self.tab_stats)
        self.label_Condition.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Condition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Condition.setObjectName("label_Condition")
        self.gridLayout_2.addWidget(self.label_Condition, 8, 0, 1, 1)
        self.label_Hearts = QtWidgets.QLabel(self.tab_stats)
        self.label_Hearts.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Hearts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Hearts.setObjectName("label_Hearts")
        self.gridLayout_2.addWidget(self.label_Hearts, 1, 2, 1, 1)
        self.label_Veils = QtWidgets.QLabel(self.tab_stats)
        self.label_Veils.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Veils.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Veils.setObjectName("label_Veils")
        self.gridLayout_2.addWidget(self.label_Veils, 2, 2, 1, 1)
        self.label_Iron = QtWidgets.QLabel(self.tab_stats)
        self.label_Iron.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Iron.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Iron.setObjectName("label_Iron")
        self.gridLayout_2.addWidget(self.label_Iron, 3, 2, 1, 1)
        self.label_Mirrors = QtWidgets.QLabel(self.tab_stats)
        self.label_Mirrors.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Mirrors.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Mirrors.setObjectName("label_Mirrors")
        self.gridLayout_2.addWidget(self.label_Mirrors, 4, 2, 1, 1)
        self.label_CharLevel = QtWidgets.QLabel(self.tab_stats)
        self.label_CharLevel.setMaximumSize(QtCore.QSize(110, 20))
        self.label_CharLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CharLevel.setObjectName("label_CharLevel")
        self.gridLayout_2.addWidget(self.label_CharLevel, 5, 2, 1, 1)
        self.label_CharPoints = QtWidgets.QLabel(self.tab_stats)
        self.label_CharPoints.setMaximumSize(QtCore.QSize(110, 20))
        self.label_CharPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CharPoints.setObjectName("label_CharPoints")
        self.gridLayout_2.addWidget(self.label_CharPoints, 6, 2, 1, 1)
        self.label_Exp = QtWidgets.QLabel(self.tab_stats)
        self.label_Exp.setMaximumSize(QtCore.QSize(110, 20))
        self.label_Exp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Exp.setObjectName("label_Exp")
        self.gridLayout_2.addWidget(self.label_Exp, 7, 2, 1, 1)
        self.tabWidget.addTab(self.tab_stats, "")
        self.tab_hold = QtWidgets.QWidget()
        self.tab_hold.setObjectName("tab_hold")
        self.tabWidget.addTab(self.tab_hold, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sunless Skies Save Editor"))
        self.pushButton_Open.setText(_translate("MainWindow", "Open"))
        self.pushButton_Save.setText(_translate("MainWindow", "Save"))
        self.pushButton_About.setText(_translate("MainWindow", "About"))
        self.label_LoadedFile.setText(_translate("MainWindow", "Loaded savefile:"))
        self.label_LoadedFileName.setText(_translate("MainWindow", "-"))
        self.label_Sovereigns.setText(_translate("MainWindow", "Sovereigns:"))
        self.label_Terror.setText(_translate("MainWindow", "Terror:"))
        self.label_Hull.setText(_translate("MainWindow", "Hull:"))
        self.label_Crew.setText(_translate("MainWindow", "Crew:"))
        self.label_Date.setText(_translate("MainWindow", "Date"))
        self.label_Hold.setText(_translate("MainWindow", "Hold:"))
        self.label_SecretComp.setText(_translate("MainWindow", "<html><head/><body><p>Secret<br>Compartments:</p></body></html>"))
        self.label_Condition.setText(_translate("MainWindow", "Condition:"))
        self.label_Hearts.setText(_translate("MainWindow", "Hearts:"))
        self.label_Veils.setText(_translate("MainWindow", "Veils:"))
        self.label_Iron.setText(_translate("MainWindow", "Iron:"))
        self.label_Mirrors.setText(_translate("MainWindow", "Mirrors:"))
        self.label_CharLevel.setText(_translate("MainWindow", "Charactrer Level:"))
        self.label_CharPoints.setText(_translate("MainWindow", "Character Points:"))
        self.label_Exp.setText(_translate("MainWindow", "Experience:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_stats), _translate("MainWindow", "Stats"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hold), _translate("MainWindow", "Hold"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
